version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=puuldb
      - POSTGRES_USER=javier
      - POSTGRES_PASSWORD=securepassword
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
#      - postgres_data:/var/lib/postgresql
#volumens:
#  postgresql-volumen:
#    external: trues
